#Env vars for cargo commands
[env]

#Activate logging lvl
RUST_LOG = "surreal_axum=debug"


# -- Config map
# In deployments this should be absolutes
SERVICE_WEB_FOLDER = "web-folder/"
SERVICE_DATABASE_PATH = "/home/nicolas/dev/rust-projects/surreal-axum/database.db/"
SERVICE_DATABASE_NAMESPACE = "surreal-axum"
SERVICE_DATABASE_DB = "surreal-axum"

